//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeVenta.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS/", ConfigurationName="ServiceReference1.ServidorWeb")]
    public interface ServidorWeb {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/actualizarUsuarioRequest", ReplyAction="http://WS/ServidorWeb/actualizarUsuarioResponse")]
        PuntoDeVenta.ServiceReference1.actualizarUsuarioResponse actualizarUsuario(PuntoDeVenta.ServiceReference1.actualizarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/altaUsuarioRequest", ReplyAction="http://WS/ServidorWeb/altaUsuarioResponse")]
        PuntoDeVenta.ServiceReference1.altaUsuarioResponse altaUsuario(PuntoDeVenta.ServiceReference1.altaUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento password del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/buscarLoginRequest", ReplyAction="http://WS/ServidorWeb/buscarLoginResponse")]
        PuntoDeVenta.ServiceReference1.buscarLoginResponse buscarLogin(PuntoDeVenta.ServiceReference1.buscarLoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/getDatarLoginRequest", ReplyAction="http://WS/ServidorWeb/getDatarLoginResponse")]
        PuntoDeVenta.ServiceReference1.getDatarLoginResponse getDatarLogin(PuntoDeVenta.ServiceReference1.getDatarLoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/getDataProductosRequest", ReplyAction="http://WS/ServidorWeb/getDataProductosResponse")]
        PuntoDeVenta.ServiceReference1.getDataProductosResponse getDataProductos(PuntoDeVenta.ServiceReference1.getDataProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/cargarUsuarioRequest", ReplyAction="http://WS/ServidorWeb/cargarUsuarioResponse")]
        PuntoDeVenta.ServiceReference1.cargarUsuarioResponse cargarUsuario(PuntoDeVenta.ServiceReference1.cargarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/bajaUsuarioRequest", ReplyAction="http://WS/ServidorWeb/bajaUsuarioResponse")]
        PuntoDeVenta.ServiceReference1.bajaUsuarioResponse bajaUsuario(PuntoDeVenta.ServiceReference1.bajaUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/getDataUsuariosRequest", ReplyAction="http://WS/ServidorWeb/getDataUsuariosResponse")]
        PuntoDeVenta.ServiceReference1.getDataUsuariosResponse getDataUsuarios(PuntoDeVenta.ServiceReference1.getDataUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/ServidorWeb/getDatarUsuariosRequest", ReplyAction="http://WS/ServidorWeb/getDatarUsuariosResponse")]
        PuntoDeVenta.ServiceReference1.getDatarUsuariosResponse getDatarUsuarios(PuntoDeVenta.ServiceReference1.getDatarUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuario", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.actualizarUsuarioRequestBody Body;
        
        public actualizarUsuarioRequest() {
        }
        
        public actualizarUsuarioRequest(PuntoDeVenta.ServiceReference1.actualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public actualizarUsuarioRequestBody() {
        }
        
        public actualizarUsuarioRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuarioResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.actualizarUsuarioResponseBody Body;
        
        public actualizarUsuarioResponse() {
        }
        
        public actualizarUsuarioResponse(PuntoDeVenta.ServiceReference1.actualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public actualizarUsuarioResponseBody() {
        }
        
        public actualizarUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class altaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="altaUsuario", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.altaUsuarioRequestBody Body;
        
        public altaUsuarioRequest() {
        }
        
        public altaUsuarioRequest(PuntoDeVenta.ServiceReference1.altaUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class altaUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public altaUsuarioRequestBody() {
        }
        
        public altaUsuarioRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class altaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="altaUsuarioResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.altaUsuarioResponseBody Body;
        
        public altaUsuarioResponse() {
        }
        
        public altaUsuarioResponse(PuntoDeVenta.ServiceReference1.altaUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class altaUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public altaUsuarioResponseBody() {
        }
        
        public altaUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarLogin", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.buscarLoginRequestBody Body;
        
        public buscarLoginRequest() {
        }
        
        public buscarLoginRequest(PuntoDeVenta.ServiceReference1.buscarLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class buscarLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public buscarLoginRequestBody() {
        }
        
        public buscarLoginRequestBody(int id, string password) {
            this.id = id;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarLoginResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.buscarLoginResponseBody Body;
        
        public buscarLoginResponse() {
        }
        
        public buscarLoginResponse(PuntoDeVenta.ServiceReference1.buscarLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class buscarLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public buscarLoginResponseBody() {
        }
        
        public buscarLoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatarLogin", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDatarLoginRequestBody Body;
        
        public getDatarLoginRequest() {
        }
        
        public getDatarLoginRequest(PuntoDeVenta.ServiceReference1.getDatarLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDatarLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public getDatarLoginRequestBody() {
        }
        
        public getDatarLoginRequestBody(string arg0, int arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatarLoginResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDatarLoginResponseBody Body;
        
        public getDatarLoginResponse() {
        }
        
        public getDatarLoginResponse(PuntoDeVenta.ServiceReference1.getDatarLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDatarLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDatarLoginResponseBody() {
        }
        
        public getDatarLoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataProductos", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDataProductosRequestBody Body;
        
        public getDataProductosRequest() {
        }
        
        public getDataProductosRequest(PuntoDeVenta.ServiceReference1.getDataProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDataProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getDataProductosRequestBody() {
        }
        
        public getDataProductosRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataProductosResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDataProductosResponseBody Body;
        
        public getDataProductosResponse() {
        }
        
        public getDataProductosResponse(PuntoDeVenta.ServiceReference1.getDataProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDataProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDataProductosResponseBody() {
        }
        
        public getDataProductosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarUsuario", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.cargarUsuarioRequestBody Body;
        
        public cargarUsuarioRequest() {
        }
        
        public cargarUsuarioRequest(PuntoDeVenta.ServiceReference1.cargarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarUsuarioRequestBody {
        
        public cargarUsuarioRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarUsuarioResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.cargarUsuarioResponseBody Body;
        
        public cargarUsuarioResponse() {
        }
        
        public cargarUsuarioResponse(PuntoDeVenta.ServiceReference1.cargarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cargarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public cargarUsuarioResponseBody() {
        }
        
        public cargarUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bajaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bajaUsuario", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.bajaUsuarioRequestBody Body;
        
        public bajaUsuarioRequest() {
        }
        
        public bajaUsuarioRequest(PuntoDeVenta.ServiceReference1.bajaUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bajaUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public bajaUsuarioRequestBody() {
        }
        
        public bajaUsuarioRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bajaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bajaUsuarioResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.bajaUsuarioResponseBody Body;
        
        public bajaUsuarioResponse() {
        }
        
        public bajaUsuarioResponse(PuntoDeVenta.ServiceReference1.bajaUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bajaUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bajaUsuarioResponseBody() {
        }
        
        public bajaUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataUsuarios", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDataUsuariosRequestBody Body;
        
        public getDataUsuariosRequest() {
        }
        
        public getDataUsuariosRequest(PuntoDeVenta.ServiceReference1.getDataUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDataUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getDataUsuariosRequestBody() {
        }
        
        public getDataUsuariosRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataUsuariosResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDataUsuariosResponseBody Body;
        
        public getDataUsuariosResponse() {
        }
        
        public getDataUsuariosResponse(PuntoDeVenta.ServiceReference1.getDataUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDataUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDataUsuariosResponseBody() {
        }
        
        public getDataUsuariosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatarUsuarios", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDatarUsuariosRequestBody Body;
        
        public getDatarUsuariosRequest() {
        }
        
        public getDatarUsuariosRequest(PuntoDeVenta.ServiceReference1.getDatarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDatarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getDatarUsuariosRequestBody() {
        }
        
        public getDatarUsuariosRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatarUsuariosResponse", Namespace="http://WS/", Order=0)]
        public PuntoDeVenta.ServiceReference1.getDatarUsuariosResponseBody Body;
        
        public getDatarUsuariosResponse() {
        }
        
        public getDatarUsuariosResponse(PuntoDeVenta.ServiceReference1.getDatarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDatarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDatarUsuariosResponseBody() {
        }
        
        public getDatarUsuariosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServidorWebChannel : PuntoDeVenta.ServiceReference1.ServidorWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServidorWebClient : System.ServiceModel.ClientBase<PuntoDeVenta.ServiceReference1.ServidorWeb>, PuntoDeVenta.ServiceReference1.ServidorWeb {
        
        public ServidorWebClient() {
        }
        
        public ServidorWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServidorWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.actualizarUsuarioResponse PuntoDeVenta.ServiceReference1.ServidorWeb.actualizarUsuario(PuntoDeVenta.ServiceReference1.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuario(request);
        }
        
        public string actualizarUsuario(string json) {
            PuntoDeVenta.ServiceReference1.actualizarUsuarioRequest inValue = new PuntoDeVenta.ServiceReference1.actualizarUsuarioRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.actualizarUsuarioRequestBody();
            inValue.Body.json = json;
            PuntoDeVenta.ServiceReference1.actualizarUsuarioResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).actualizarUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.altaUsuarioResponse PuntoDeVenta.ServiceReference1.ServidorWeb.altaUsuario(PuntoDeVenta.ServiceReference1.altaUsuarioRequest request) {
            return base.Channel.altaUsuario(request);
        }
        
        public string altaUsuario(string json) {
            PuntoDeVenta.ServiceReference1.altaUsuarioRequest inValue = new PuntoDeVenta.ServiceReference1.altaUsuarioRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.altaUsuarioRequestBody();
            inValue.Body.json = json;
            PuntoDeVenta.ServiceReference1.altaUsuarioResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).altaUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.buscarLoginResponse PuntoDeVenta.ServiceReference1.ServidorWeb.buscarLogin(PuntoDeVenta.ServiceReference1.buscarLoginRequest request) {
            return base.Channel.buscarLogin(request);
        }
        
        public string buscarLogin(int id, string password) {
            PuntoDeVenta.ServiceReference1.buscarLoginRequest inValue = new PuntoDeVenta.ServiceReference1.buscarLoginRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.buscarLoginRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            PuntoDeVenta.ServiceReference1.buscarLoginResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).buscarLogin(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.getDatarLoginResponse PuntoDeVenta.ServiceReference1.ServidorWeb.getDatarLogin(PuntoDeVenta.ServiceReference1.getDatarLoginRequest request) {
            return base.Channel.getDatarLogin(request);
        }
        
        public string getDatarLogin(string arg0, int arg1, string arg2) {
            PuntoDeVenta.ServiceReference1.getDatarLoginRequest inValue = new PuntoDeVenta.ServiceReference1.getDatarLoginRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.getDatarLoginRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            PuntoDeVenta.ServiceReference1.getDatarLoginResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).getDatarLogin(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.getDataProductosResponse PuntoDeVenta.ServiceReference1.ServidorWeb.getDataProductos(PuntoDeVenta.ServiceReference1.getDataProductosRequest request) {
            return base.Channel.getDataProductos(request);
        }
        
        public string getDataProductos(string arg0, string arg1) {
            PuntoDeVenta.ServiceReference1.getDataProductosRequest inValue = new PuntoDeVenta.ServiceReference1.getDataProductosRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.getDataProductosRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            PuntoDeVenta.ServiceReference1.getDataProductosResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).getDataProductos(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.cargarUsuarioResponse PuntoDeVenta.ServiceReference1.ServidorWeb.cargarUsuario(PuntoDeVenta.ServiceReference1.cargarUsuarioRequest request) {
            return base.Channel.cargarUsuario(request);
        }
        
        public string cargarUsuario() {
            PuntoDeVenta.ServiceReference1.cargarUsuarioRequest inValue = new PuntoDeVenta.ServiceReference1.cargarUsuarioRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.cargarUsuarioRequestBody();
            PuntoDeVenta.ServiceReference1.cargarUsuarioResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).cargarUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.bajaUsuarioResponse PuntoDeVenta.ServiceReference1.ServidorWeb.bajaUsuario(PuntoDeVenta.ServiceReference1.bajaUsuarioRequest request) {
            return base.Channel.bajaUsuario(request);
        }
        
        public string bajaUsuario(string json) {
            PuntoDeVenta.ServiceReference1.bajaUsuarioRequest inValue = new PuntoDeVenta.ServiceReference1.bajaUsuarioRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.bajaUsuarioRequestBody();
            inValue.Body.json = json;
            PuntoDeVenta.ServiceReference1.bajaUsuarioResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).bajaUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.getDataUsuariosResponse PuntoDeVenta.ServiceReference1.ServidorWeb.getDataUsuarios(PuntoDeVenta.ServiceReference1.getDataUsuariosRequest request) {
            return base.Channel.getDataUsuarios(request);
        }
        
        public string getDataUsuarios(string arg0, string arg1) {
            PuntoDeVenta.ServiceReference1.getDataUsuariosRequest inValue = new PuntoDeVenta.ServiceReference1.getDataUsuariosRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.getDataUsuariosRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            PuntoDeVenta.ServiceReference1.getDataUsuariosResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).getDataUsuarios(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoDeVenta.ServiceReference1.getDatarUsuariosResponse PuntoDeVenta.ServiceReference1.ServidorWeb.getDatarUsuarios(PuntoDeVenta.ServiceReference1.getDatarUsuariosRequest request) {
            return base.Channel.getDatarUsuarios(request);
        }
        
        public string getDatarUsuarios(string arg0, string arg1) {
            PuntoDeVenta.ServiceReference1.getDatarUsuariosRequest inValue = new PuntoDeVenta.ServiceReference1.getDatarUsuariosRequest();
            inValue.Body = new PuntoDeVenta.ServiceReference1.getDatarUsuariosRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            PuntoDeVenta.ServiceReference1.getDatarUsuariosResponse retVal = ((PuntoDeVenta.ServiceReference1.ServidorWeb)(this)).getDatarUsuarios(inValue);
            return retVal.Body.@return;
        }
    }
}
